# Generated by Django 4.2.2 on 2023-06-09 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmy_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('director', models.CharField(blank=True, max_length=200, null=True)),
                ('genres', models.ManyToManyField(to='filmy_app.gatunek')),
            ],
        ),
    ]
