# Generated by Django 4.2.2 on 2023-06-09 18:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('filmy_app', '0003_recenzent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Opinia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(null=True)),
                ('film', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='filmy_app.film')),
                ('recenzent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='filmy_app.recenzent')),
            ],
        ),
    ]
